# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  """The add service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddNumbers = channel.unary_unary(
        '/calculator.Calculator/AddNumbers',
        request_serializer=calculator__pb2.AddRequest.SerializeToString,
        response_deserializer=calculator__pb2.AddReponse.FromString,
        )


class CalculatorServicer(object):
  """The add service definition.
  """

  def AddNumbers(self, request, context):
    """perform addition
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.AddNumbers,
          request_deserializer=calculator__pb2.AddRequest.FromString,
          response_serializer=calculator__pb2.AddReponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
